# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_bestSPLS_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_bestSPLS_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_bestSPLS_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_bestSPLS_rcpparma_bothproducts`, x)
}

Ust <- function(b, eta) {
    .Call(`_bestSPLS_Ust`, b, eta)
}

case_1 <- function(M, c, eps, maxstep, eta) {
    .Call(`_bestSPLS_case_1`, M, c, eps, maxstep, eta)
}

